#!/bin/bash
ddir="/Users/jcrane10/git/sivic/applications/scanner/GE_console/docker"
echo "docker run -v ${ddir}/freeware:/data/freeware -v ${ddir}/netopt:/netopt -v ${ddir}/opt:/opt -i -t sivic_centos68 /bin/bash"
exit

#   create image from dockerfile:
docker build -t sivic_centos68 ./

docker create sivic_centos68



#docker run -v /Users/jcrane10/docker/sivic_ge_dist/freeware:/data/freeware -v /Users/jcrane10/docker/sivic_ge_dist/netopt:/netopt -i -t sivic_centos68 /bin/bash

docker run -v ${ddir}/freeware:/data/freeware -v ${ddir}/netopt:/netopt -v ${ddir}/opt:/opt -i -t sivic_centos68 /bin/bash


