#
#   This file was auto-generated by my.cdash.org and downloaded into this project. 
#   should be run from cron on host machines with correct architecture, e.g.:
#       23 20 * * * cd /data/lhst3/sivic/svn/sivic/trunk; /netopt/bin/ctest -D Nightly --output-log /data/lhst3/sivic/ctest_logs/atom
#
#
## This file should be placed in the root directory of your project.
## Then modify the CMakeLists.txt file in the root directory of your
## project to incorporate the testing dashboard.
## # The following are required to uses Dart and the Cdash dashboard
##   ENABLE_TESTING()
##   INCLUDE(CTest)
set(CTEST_PROJECT_NAME "SIVIC")
set(CTEST_NIGHTLY_START_TIME "00:00:00 PST")
#set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=SIVIC")
set(CTEST_DROP_SITE_CDASH TRUE)
