#
#   This file was auto-generated by my.cdash.org and downloaded into this project. 
#   should be run from cron on host machines with correct architecture, e.g.:
#
#   sivic nightly testing and cdash upload on atom (lx64)
#   07 00 * * * cd /data/lhst3/sivic/svn/sivic; make -f Makefile.ctest nightly > /dev/null
#   07 01 * * * cd /data/lhst3/sivic/svn/sivic; make -f Makefile.ctest experimental > /dev/null


#
#
## This file should be placed in the root directory of your project.
## Then modify the CMakeLists.txt file in the root directory of your
## project to incorporate the testing dashboard.
## # The following are required to uses Dart and the Cdash dashboard
## #ENABLE_TESTING()
## #INCLUDE(CTest)
set(CTEST_PROJECT_NAME "SIVIC")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=SIVIC")
set(CTEST_DROP_SITE_CDASH TRUE)
