#!/usr/bin/perl 

#
#  Copyright © 2009-2014 The Regents of the University of California.
#  All Rights Reserved.
#
#  Redistribution and use in source and binary forms, with or without 
#  modification, are permitted provided that the following conditions are met:
#  •   Redistributions of source code must retain the above copyright notice, 
#      this list of conditions and the following disclaimer.
#  •   Redistributions in binary form must reproduce the above copyright notice, 
#      this list of conditions and the following disclaimer in the documentation 
#      and/or other materials provided with the distribution.
#  •   None of the names of any campus of the University of California, the name 
#      "The Regents of the University of California," or the names of any of its 
#      contributors may be used to endorse or promote products derived from this 
#      software without specific prior written permission.
#  
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
#  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
#  OF SUCH DAMAGE.
#

#
#   $URL: https://intrarad.ucsf.edu/svn/rad_software/surbeck/common/scanners/data_browser/trunk/svk/installer $
#   $Rev: 30662 $
#   $Author: jasonc@RADIOLOGY.UCSF.EDU $
#   $Date: 2014-02-19 10:42:21 -0800 (Wed, 19 Feb 2014) $
#
#   Authors:
#       Jason Crane, PhD
#       Beck Olson
#

#   Department of Radiology and Biomedical Imaging 
#   University of California, San Francisco
#


$ROOT_DIR   = "svk"; 
system( "mkdir $ROOT_DIR" ) ; 
system( "cp -r bin  $ROOT_DIR" ); 
system( "cp -r lib  $ROOT_DIR" ); 
system( "cp -r data $ROOT_DIR" ); 

#   include other system commands: 
system ("cp /netopt/dicom/bin/dcmdump       ./svk/bin "); 
system ("cp /netopt/share/dcmtk/dicom.dic   ./svk/lib "); 

#   remove .svn files
$cmd = "find ./svk -name \'*.svn\' | xargs rm -rf "; 
system("$cmd"); 


