#!/usr/bin/perl 

#
#  Copyright © 2009-2017 The Regents of the University of California.
#  All Rights Reserved.
#
#  Redistribution and use in source and binary forms, with or without 
#  modification, are permitted provided that the following conditions are met:
#  •   Redistributions of source code must retain the above copyright notice, 
#      this list of conditions and the following disclaimer.
#  •   Redistributions in binary form must reproduce the above copyright notice, 
#      this list of conditions and the following disclaimer in the documentation 
#      and/or other materials provided with the distribution.
#  •   None of the names of any campus of the University of California, the name 
#      "The Regents of the University of California," or the names of any of its 
#      contributors may be used to endorse or promote products derived from this 
#      software without specific prior written permission.
#  
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
#  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
#  OF SUCH DAMAGE.
#

#
#   $URL: https://intrarad.ucsf.edu/svn/rad_software/surbeck/brain/sat_placement_atlas_based/trunk/svk_atlas_auto_mrsi_start $
#   $Rev: 39349 $
#   $Author: bolson@RADIOLOGY.UCSF.EDU $
#   $Date: 2017-01-24 16:17:11 -0800 (Tue, 24 Jan 2017) $
#
#   Jason C. Crane, Ph.D.
#   Department of Radiology and Biomedical Imaging
#   University of California, San Francisco
#

#   should be initiated from more_software via the following entry in /opt/local/etc/more_software.cfg
#   7T MRSI ATLAS SAT Placement | /export/home/sdc/svk/console/bin/svk_Atlas_Based_Auto_MRSI_Prescription/svk_atlas_auto_mrsi_start 


use strict;
use lib "$ENV{HOME}/svk/console/lib";
use svk_ge_util;
use svk_ge_data_browser_conf;
use Getopt::Long;
Getopt::Long::config("bundling");

sub clean_local();

my $auto_sats_bin_dir = "$ENV{HOME}/svk/console/packages/Atlas_Based_Auto_MRSI_Prescription";
my $config_file = "${auto_sats_bin_dir}/svk_atlas_auto_mrsi_start.cfg";

GetOptions(
	"c=s"   => \$config_file 
);

my $scanner_work_dir = "$svk_ge_data_browser_conf::scanner_work_dir";

#   get command, optional flags, and data refs
my %command = svk_ge_browser_get_command($config_file);
my $prog  = $command{prog};
my $flags = $command{flags};
my($reference) = split /\s+/, $command{files};


my($exam_dir);
if($reference =~ m/\/e(\d+)/) {
    $exam_dir = "E$1";
}
print "EXAM: $exam_dir\n"; 


#   construct program cmd string
#   Both exam series (reference and AC get transmitted) 
$prog = "${auto_sats_bin_dir}/svk_atlas_auto_mrsi_local"; 
$prog .= " -s $scanner_work_dir";
$prog .= " -e $exam_dir";
if ( defined $flags ) {
    $prog .= " $flags"; 
}

print "program to run: $prog\n"; 
my $status = svk_ge_run_program('local', "$prog");
print "program done running status: $status\n"; 

#
#   If recon completed, then finalize 
#
if (!$status) {
    svk_ge_write_local_status($scanner_work_dir, 0);
} else {
    print "ERROR PROCESSING DATA\n";
}

#
#   finalize threads, then return to clean up local data
#
svk_ge_finalize();

