#!/usr/bin/perl 

#
#  Copyright © 2009-2017 The Regents of the University of California.
#  All Rights Reserved.
#
#  Redistribution and use in source and binary forms, with or without 
#  modification, are permitted provided that the following conditions are met:
#  •   Redistributions of source code must retain the above copyright notice, 
#      this list of conditions and the following disclaimer.
#  •   Redistributions in binary form must reproduce the above copyright notice, 
#      this list of conditions and the following disclaimer in the documentation 
#      and/or other materials provided with the distribution.
#  •   None of the names of any campus of the University of California, the name 
#      "The Regents of the University of California," or the names of any of its 
#      contributors may be used to endorse or promote products derived from this 
#      software without specific prior written permission.
#  
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
#  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
#  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
#  OF SUCH DAMAGE.
#

#
#   $URL: https://intrarad.ucsf.edu/svn/rad_software/surbeck/brain/sat_placement_atlas_based/trunk/svk_atlas_auto_mrsi_local $
#   $Rev: 39349 $
#   $Author: bolson@RADIOLOGY.UCSF.EDU $
#   $Date: 2017-01-24 16:17:11 -0800 (Tue, 24 Jan 2017) $
#
#   Jason C. Crane, Ph.D.
#   Department of Radiology and Biomedical Imaging
#   University of California, San Francisco
#

use strict;
use lib "$ENV{HOME}/svk/console/lib";
use svk_ge_util;
use svk_ge_data_browser_conf;
use Getopt::Long;
Getopt::Long::config("bundling");


GetOptions(
           "e=s"  => \my $exam_dir,
           "s=s"  => \my $scanner_work_dir
);


my $matlab_dir = "$ENV{HOME}/svk/console/lib/matlab/v717"; 

my $pkg = "Atlas_Based_Auto_MRSI_Prescription"; 
my $auto_sats_pkg_dir = "$ENV{HOME}/svk/console/packages/${pkg}/"; 
my $matlab_pkg_dir = "${auto_sats_pkg_dir}/${pkg}_matlab"; 
my $atlas_dir = "${auto_sats_pkg_dir}/atlas_prescription"; 
my $output_dir = "/usr/g/research/mrs"; 

# get series directory: 
my $regist_dir = glob("${scanner_work_dir}/$exam_dir/*"); 

my $cmd  = "${matlab_pkg_dir}/run_Atlas_Based_Auto_MRSI_Prescription.sh ${matlab_dir} "; 
$cmd    .= "'atlas_dir' '${atlas_dir}' ";
$cmd    .= "'regist_dir' '${regist_dir}' ";
$cmd    .= "'output_dir' '${output_dir}' ";
$cmd    .= "'flirt_dir' '${auto_sats_pkg_dir}/bin/' ";

print "\n$cmd \n\n";

if ( system( ${cmd} ) ) {
    svk_ge_write_local_status($scanner_work_dir, 1);
    exit(1);
}

# if everything completed, then write status = 0: 
svk_ge_write_local_status($scanner_work_dir, 0);

