#!/usr/bin/perl -w
# 
#   Copyright © 2009-2011 The Regents of the University of California.
#   All Rights Reserved.
# 
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#   •   Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#   •   Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#   •   None of the names of any campus of the University of California, the name
#       "The Regents of the University of California," or the names of any of its
#       contributors may be used to endorse or promote products derived from this
#       software without specific prior written permission.
# 
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#   IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
#   INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
#   OF SUCH DAMAGE.
# /

#   $URL$
#   $Rev$
#   $Author$
#   $Date$
#
#   This script uses dcmtk's dcm2xml script to diff dicom images. 
#

use strict;
use Getopt::Long;
Getopt::Long::config("bundling");
use Pod::Usage;
use Cwd;
use Cwd 'abs_path';

sub exit_gracefully( $ );

GetOptions(
    "src_dir=s"     => \my $src_dir,
    "target_dir=s"  => \my $target_dir,
    "raw_root=s"     => \my $raw_root,
    "v"             => \my $verbose,
    "help"          => \my $help,
) or pod2usage(-verbose=>2, -exitval=>2);

if( !defined($src_dir) || !defined($target_dir) || !defined($raw_root) || defined($help) ) {
    pod2usage(-verbose=>2, -exitval=>2);
}



my $ln_cmd = "/bin/ln -f -s ${src_dir}/${raw_root}* -t ${target_dir}"; 

if( system("$ln_cmd") != 0 ) {
    exit(1); 
}



###############################################################################
#
#   POD Usage docs
#
###############################################################################

=head1 NAME

raw_links

=head1 SYNOPSIS

raw_links --src_dir dir --target_dir --root root 

        -v                        display debugging messages
        --help                    print usage message
        --bin_dir                 bin directory for dcm2xml 

=head1 DESCRIPTION

diffs the xml 

EXAMPLE:

    dcm2xml_series_diff --dir_one series_one --dir_two series_two --diff_opts  "--ignore-matching-lines=UID --exclude=.svn"

=cut

